[build]
publish = "public"
HUGO_ENV = "production"
command = "hugo --gc --minify --baseURL $URL"

[context.deploy-preview]
HUGO_ENABLEGITINFO = "true"
command = "hugo --gc --minify --buildFuture --baseURL $DEPLOY_PRIME_URL"
